#!/usr/bin/env python3
"""One-shot script: create the aischool-ielts-bj OSS bucket (if absent),
set public-read ACL, and upload all 40 interactive HTMLs + pronunciations.json
with the correct MIME types.

OSS public URL pattern after upload:
  https://aischool-ielts-bj.oss-cn-beijing.aliyuncs.com/<filename>

Run:  python scripts/upload_to_oss.py

Reads AccessKey from env: ALIYUN_ACCESS_KEY_ID, ALIYUN_ACCESS_KEY_SECRET.
"""
from __future__ import annotations
import os
import sys
from pathlib import Path

import oss2

REPO = Path(__file__).resolve().parents[1]
BUCKET_NAME = "aischool-ielts-bj"
ENDPOINT = "https://oss-cn-beijing.aliyuncs.com"


def main() -> int:
    ak = os.environ.get("ALIYUN_ACCESS_KEY_ID")
    sk = os.environ.get("ALIYUN_ACCESS_KEY_SECRET")
    if not ak or not sk:
        print("error: ALIYUN_ACCESS_KEY_ID and ALIYUN_ACCESS_KEY_SECRET env vars required",
              file=sys.stderr)
        return 2

    auth = oss2.Auth(ak, sk)
    service = oss2.Service(auth, ENDPOINT)

    # 1. Check if bucket exists; create if absent with public-read ACL.
    existing = [b.name for b in oss2.BucketIterator(service)]
    bucket = oss2.Bucket(auth, ENDPOINT, BUCKET_NAME)
    if BUCKET_NAME in existing:
        print(f"Bucket '{BUCKET_NAME}' already exists.")
        # Ensure public-read ACL.
        try:
            bucket.put_bucket_acl(oss2.BUCKET_ACL_PUBLIC_READ)
            print(f"  ACL set to public-read.")
        except Exception as e:
            print(f"  warning: could not update ACL ({e}).")
    else:
        bucket.create_bucket(oss2.BUCKET_ACL_PUBLIC_READ)
        print(f"Created bucket '{BUCKET_NAME}' with public-read ACL in cn-beijing.")

    # 2. Upload 40 interactive HTMLs with Text/HTML mime.
    interactive = REPO / "Interactive"
    htmls = sorted(interactive.glob("Week_*.html"))
    print(f"\nUploading {len(htmls)} HTML files...")
    for f in htmls:
        bucket.put_object_from_file(
            f.name,
            str(f),
            headers={"Content-Type": "Text/HTML; charset=utf-8"},
        )
        print(f"  [ok] {f.name}")

    # 3. Upload pronunciations.json.
    pron = REPO / "pronunciations.json"
    if pron.exists():
        bucket.put_object_from_file(
            "pronunciations.json",
            str(pron),
            headers={"Content-Type": "application/json; charset=utf-8"},
        )
        print(f"  [ok] pronunciations.json")
    else:
        print("  WARN: pronunciations.json not found at repo root", file=sys.stderr)

    # 3b. Upload index.html landing page — generated by build_landing_page.py.
    # Auto-regenerate first if it's missing OR older than the most recent
    # Week_*.html file (so re-uploads after curriculum updates pick up new
    # week topics in the landing-page cards).
    index_path = REPO / "index.html"
    needs_rebuild = not index_path.exists()
    if not needs_rebuild:
        index_mtime = index_path.stat().st_mtime
        for w in REPO.glob("Week_*.html"):
            if w.stat().st_mtime > index_mtime:
                needs_rebuild = True
                break
    if needs_rebuild:
        import subprocess
        print(f"  [info] index.html stale or missing — regenerating via build_landing_page.py")
        subprocess.run([sys.executable, str(REPO / "scripts" / "build_landing_page.py")],
                       check=True, cwd=str(REPO))
    if index_path.exists():
        bucket.put_object_from_file(
            "index.html", str(index_path),
            headers={"Content-Type": "text/html; charset=utf-8"},
        )
        print(f"  [ok] index.html")
    else:
        print("  WARN: index.html not found and build_landing_page.py failed", file=sys.stderr)

    # 4. Upload images/*.png — required for the <img src="images/foo.png">
    # references inside each Week_NN.html. Without this step, all weeks
    # render with broken-image placeholders for the course pipeline diagrams.
    # We prefer the Interactive/images/ folder (matches what was just uploaded);
    # fall back to repo root images/ if Interactive/images/ is missing.
    candidates = [REPO / "Interactive" / "images", REPO / "images"]
    src_images = next((p for p in candidates if p.is_dir()), None)
    if src_images is None:
        print("  WARN: no images/ folder found at Interactive/images or repo root — "
              "skipping image upload", file=sys.stderr)
    else:
        mime_by_ext = {".png": "image/png", ".jpg": "image/jpeg", ".jpeg": "image/jpeg",
                       ".webp": "image/webp", ".svg": "image/svg+xml", ".gif": "image/gif"}
        img_count = 0
        for img in sorted(src_images.iterdir()):
            if img.is_file() and img.suffix.lower() in mime_by_ext:
                bucket.put_object_from_file(
                    f"images/{img.name}", str(img),
                    headers={"Content-Type": mime_by_ext[img.suffix.lower()]},
                )
                print(f"  [ok] images/{img.name}")
                img_count += 1
        print(f"Uploaded {img_count} image(s) from {src_images}")

    print(f"\nPublic base URL:")
    print(f"  https://{BUCKET_NAME}.oss-cn-beijing.aliyuncs.com/")
    print(f"\nSample file:")
    print(f"  https://{BUCKET_NAME}.oss-cn-beijing.aliyuncs.com/Week_1_Lesson_Plan.html")
    return 0


if __name__ == "__main__":
    sys.exit(main())
